services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    command: npm run start:prod
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis
    ports:
      - 6379:6379
    command:
    - /bin/sh
    - -c
    - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
    - redis:/var/lib/redis/data
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data


volumes:
  redis:
    driver: local
  docker-nest-postgres:
    driver: local
