jwt:
  secret: 'secret'
  expiry: '259200s'

admins:
  - 'admin emails'

googleOauth:
  clientId: 'clientID'
  clientSecret: 'slientSecret'
  callbackUrl: 'callbackurl'

redirectUrl: 'http://rc2023.acmvit.in/auth/google/redirect'
